apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
     matchLabels:
        name: gitlab
        app: gitlab
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:9.5.6-ce.0
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Berlin
        - name: GITLAB_TIMEZONE
          value: Berlin
        - name: DEBUG
          value: "false"

        # - name: GITLAB_SECRETS_DB_KEY_BASE
        #   value: P26qS5+Csz50Dkd0DLM2oN9owVBFg0PB
        # - name: GITLAB_SECRETS_SECRET_KEY_BASE
        #   value: KVaMTKLAIElEp0s4L02c1O9JCP0Rfapb
        # - name: GITLAB_SECRETS_OTP_KEY_BASE
        #   value: nXJJ358Qnci0yF9qpAsLrF2vImaoFR03

        - name: GITLAB_ROOT_PASSWORD
          value: password
        - name: GITLAB_ROOT_EMAIL
          value: sandeep.alguri@walkingtree.tech

        - name: GITLAB_HOST
          value: "192.168.111.162:30050"
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_HOST
          value: "ssh-git.example.com"
        - name: GITLAB_SSH_PORT
          value: "1022"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: gitlab-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: password
        - name: DB_NAME
          value: gitlab_test

        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: ""
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASS
          value: ""
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: gitdata
        livenessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 65
        readinessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 360
          timeoutSeconds: 45
      volumes:
        - name: gitdata
          persistentVolumeClaim:
            claimName: gitlabimp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlabimp
  namespace: gitlab
spec:
        #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlabimp
  namespace: gitlab
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
    #  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
